import type { Metadata } from "next";
import Navbar from "./components/Navbar/Navbar";
import { Open_Sans } from "next/font/google";
import TilesMenu from "./components/TilesMenu/TilesMenu";
import 'swiper/css';
import 'swiper/css/pagination';
import "./globals.scss";

const openSans = Open_Sans({
  subsets: ["latin"], // Subconjuntos de caracteres
  weight: ["300", "400", "600", "700"], // Pesos que quieres usar
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <Navbar />
        <TilesMenu/>
        {children}
      </body>
    </html>
  );
}
